nodes:
  - id: mnode1
  - id: mnode2
  - id: mnode3
  - id: mnode4
  - id: mnode5
  - id: mnode6
  - id: mnode7
  - id: mnode8
  - id: mnode9
  - id: mnode10
  - id: mnode11
  - id: mnode12
  - id: mnode13
  - id: mnode14
  - id: mnode15
  - id: mnode16
  - id: mnode17
  - id: mnode18
  - id: mnode19
  - id: mnode20
  - id: mnode21
  - id: mnode22
  - id: mnode23
  - id: mnode24
  - id: mnode25
  - id: mnode26
  - id: mnode27
  - id: mnode28
  - id: mnode29
  - id: mnode30
  - id: mnode31
  - id: mnode32
  - id: mnode33
  - id: mnode34
  - id: mnode35
  - id: mnode36
  - id: mnode37
  - id: mnode38
